export enum AutoActionName {
    AutoActionRoot = 'AutoActionRoot',
    AutoActionClick = 'AutoActionClick',
    AutoActionCheckGroup  = 'AutoActionCheckGroup',
    AutoActionCheck  = 'AutoActionCheck',
    AutoActionGetText  = 'AutoActionGetText',
    AutoActionEnterText = 'AutoActionEnterText',
    AutoActionWait  = 'AutoActionWait',
    AutoActionScrollIntoView  = 'AutoActionScrollIntoView',
    AutoActionSelectFile  = 'AutoActionSelectFile',
    AutoActionWaitUntil  = 'AutoActionWaitUntil',
    AutoActionSetValue = 'AutoActionSetValue',
    AutoActionCase = 'AutoActionCase',
    AutoActionDragNDrop = 'AutoActionDragNDrop',
    AutoActionUrl = 'AutoActionUrl',
    AutoActionFocus = 'AutoActionFocus',
    AutoActionProcedure = 'AutoActionProcedure',
    AutoActionEmpty = 'AutoActionEmpty',
    AutoActionConsoleLog = 'AutoActionConsoleLog',
    AutoActionGoTo = 'AutoActionGoTo',
    AutoActionGroup = 'AutoActionGroup',
    AutoActionCaseParameter = 'AutoActionCaseParameter'
}
